# .github/workflows/php.yml
name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List all files in repo
        run: ls -la

      - name: Copy files to remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}

          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}

        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts

          # Copy all files
          scp -r ./* "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"

      - name: Update SQL Data
        run: |
          ssh -i "SSH_PRIVATE_KEY $REMOTE_USER@$REMOTE_HOST" 
          echo 'Connected to server successfully';

          sudo mysql -u root starandblooms < /var/www/html/db_scripts_update.sql
          echo 'Database has updated';
